### ISSUE TITLE
Can I use this without pgtrigger?

### ISSUE THREAD

**Issue by spapas** [PaulGilmartin/django-pgpubsub#85]
When I try to use this project without adding pgtrigger to my INSTALLED_APPS I get the following error:

Please notice I don't use any Trigger related channels or functionality.

```
Traceback (most recent call last):
  File "C:\progr\py3\pycensus\pycensus\manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\serafeim\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\pgpubsub\models.py", line 17, in <module>
    class Notification(models.Model):
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\db\models\base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\db\models\base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\progr\py3\pycensus\venv\Lib\site-packages\django\db\models\options.py", line 220, in contribute_to_class
    raise TypeError(
TypeError: 'class Meta' got invalid attribute(s): triggers
```

**Comment by PaulGilmartin** [comment]
@spapas Thanks for your interest in this library! Adding `pgtrigger` to INSTALLED_APPS is currently a requirement. `pgtrigger` is currently one of this library's mandatory external dependencies. In hindsight it could be optional, because as you point out you can use this library without using triggers, but unfortunately that's not the way it is just now.

**Comment by spapas** [comment]
@PaulGilmartin makes sense thank you!
